const RobotActionType = {
    SEARCH_ROBOTS_START : "SEARCH_ROBOTS_START",
    SEARCH_ROBOTS_SUCCESS : "SEARCH_ROBOTS_SUCCESS",
    SEARCH_ROBOTS_FAILURE : "SEARCH_ROBOTS_FAILURE"
}

export default RobotActionType;